# Generated by Django 5.2.4 on 2025-08-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.CharField(blank=True, choices=[('0-6months', 'Less than 6 months'), ('6-12months', '6-12 months'), ('1-2years', '1-2 years'), ('2plus', '2+ years')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('now', 'Available now'), ('soon', 'Available soon')], default='now', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='box_accessories',
            field=models.CharField(blank=True, choices=[('box', 'Has original box'), ('accessories', 'Has all accessories'), ('missing', 'Missing items')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('intel', 'Intel'), ('amd', 'AMD'), ('nvidia', 'NVIDIA'), ('asus', 'ASUS'), ('msi', 'MSI'), ('corsair', 'Corsair'), ('gigabyte', 'Gigabyte'), ('evga', 'EVGA'), ('samsung', 'Samsung'), ('western-digital', 'Western Digital')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='compatibility',
            field=models.CharField(blank=True, choices=[('lga1700', 'LGA1700'), ('am4', 'AM4'), ('am5', 'AM5'), ('ddr4', 'DDR4'), ('ddr5', 'DDR5'), ('atx', 'ATX'), ('micro-atx', 'Micro-ATX'), ('mini-itx', 'Mini-ITX')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='performance_tier',
            field=models.CharField(blank=True, choices=[('entry', 'Entry level'), ('mid', 'Mid-range'), ('high', 'High-end')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fixed price'), ('negotiable', 'Price negotiable')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, choices=[('under', 'Under warranty'), ('expired', 'Warranty expired'), ('none', 'No warranty info')], max_length=20, null=True),
        ),
    ]
