# Generated by Django 5.2.4 on 2025-08-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_product_age_product_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.CharField(choices=[('0-6months', 'Less than 6 months'), ('6-12months', '6-12 months'), ('1-2years', '1-2 years'), ('2plus', '2+ years')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='box_accessories',
            field=models.CharField(choices=[('box', 'Has original box'), ('accessories', 'Has all accessories'), ('missing', 'Missing items')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('intel', 'Intel'), ('amd', 'AMD'), ('nvidia', 'NVIDIA'), ('asus', 'ASUS'), ('msi', 'MSI'), ('corsair', 'Corsair'), ('gigabyte', 'Gigabyte'), ('evga', 'EVGA'), ('samsung', 'Samsung'), ('western-digital', 'Western Digital')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='performance_tier',
            field=models.CharField(choices=[('entry', 'Entry level'), ('mid', 'Mid-range'), ('high', 'High-end')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(choices=[('under', 'Under warranty'), ('expired', 'Warranty expired'), ('none', 'No warranty info')], max_length=20, null=True),
        ),
    ]
