# Generated by Django 5.2.4 on 2025-08-01 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerComponentOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer', models.CharField(max_length=30)),
                ('retailer_name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('availability', models.BooleanField(default=True)),
                ('category', models.CharField(max_length=50)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='components.component')),
            ],
        ),
    ]
