# Generated by Django 5.2.4 on 2025-08-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_retailercomponentoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailercomponentoffer',
            name='model_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
